apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: kubearmor-relay-kubearmor-kubearmor-relay-server-latest-write-under-dev-dir
  namespace: kube-system
spec:
  action: Audit
  file:
    matchDirectories:
    - dir: /dev/
      readOnly: true
      recursive: true
  message: Alert! File creation under /dev/ directory detected.
  selector:
    matchLabels:
      kubearmor-app: kubearmor-relay
  severity: 5
  tags:
  - NIST
  - NIST_800-53_AU-2
  - NIST_800-53_SI-4
  - MITRE
  - MITRE_T1036_masquerading
