apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: kubearmor-relay-kubearmor-kubearmor-relay-server-latest-impair-defense
  namespace: kube-system
spec:
  action: Audit
  file:
    matchDirectories:
    - dir: /etc/apparmor.d/
      recursive: true
    - dir: /etc/sysconfig/selinux/
      recursive: true
    matchPaths:
    - path: /etc/selinux/semanage.conf
  message: Selinux Files Accessed by Unknown Process
  selector:
    matchLabels:
      kubearmor-app: kubearmor-relay
  severity: 6
  tags:
  - MITRE
  - FGT1562
  - FIGHT
