apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: kubearmor-relay-kubearmor-kubearmor-relay-server-latest-remote-services
  namespace: kube-system
spec:
  action: Audit
  file:
    matchDirectories:
    - dir: /etc/ssh/
    matchPaths:
    - path: /var/log/wtmp
    - path: /var/run/utmp
    - path: /var/log/auth.log
    - path: /etc/passwd
    - path: /etc/shadow
  message: Warning! access sensitive files detected
  selector:
    matchLabels:
      kubearmor-app: kubearmor-relay
  severity: 3
  tags:
  - MITRE
  - FIGHT
  - FGT1021
