apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: discovery-engine-accuknox-knoxautopolicy-stable-file-system-mounts
  namespace: accuknox-agents
spec:
  action: Audit
  message: Alert! file system mount detected
  process:
    matchPaths:
    - path: /bin/mount
    - path: /usr/bin/mount
    - path: /bin/umount
    - path: /usr/bin/umount
  selector:
    matchLabels:
      app: discovery-engine
  severity: 5
  tags:
  - CIS
  - CIS_Linux
  - CIS_4_Logging_and_Aduditing
  - CIS_4.1.1_Data_Retention
  - CIS_4.1.14_file_system_mount
