apiVersion: v1
kind: Pod
metadata:
  labels:
    run: watch-env
  name: test-envvars-secrets-watch
  namespace: my-ext-secret
spec:
  containers:
  - image: ubuntu:22.04
    name: test
    resources: {}
    command:
    - bash
    - -c
    - 'while [[ 1 == 1 ]]; do date && env | grep MY_SECRET_PASSWORD && sleep 1; done'
    env:
    - name: MY_SECRET_PASSWORD
      valueFrom:
        secretKeyRef:
          name: secret-to-be-created
          key: somepassword
  dnsPolicy: ClusterFirst
  restartPolicy: Never