apiVersion: v1
kind: Pod
metadata:
  labels:
    run: test
  name: test-envvars-secrets 
  namespace: my-ext-secret
spec:
  containers:
  - image: busybox
    name: test
    resources: {}
    command:
    - env
    env:
    - name: MY_SECRET_PASSWORD
      valueFrom:
        secretKeyRef:
          name: secret-to-be-created
          key: somepassword
  dnsPolicy: ClusterFirst
  restartPolicy: Never