---
apiVersion: openunison.tremolo.io/v1
kind: Workflow
metadata:
  name: new-application-production
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: openunison
    app.kubernetes.io/instance: openunison-{{ .Release.Name }}
    app.kubernetes.io/component: openunison-workflows
    app.kubernetes.io/part-of: openunison
spec:
  description: create production application infrastructure
  inList: false
  label: new application in production
  orgId: 43625c4c-43a5-4e48-89da-7005a60cfcff
  dynamicConfiguration:
    dynamic: false
    className: ""
    params: []
  tasks: |-
    # create an operations project in gitlab
    - taskType: customTask
      className: com.tremolosecurity.unison.gitlab.provisioning.tasks.CreateProject
      params:
        namespace: $nameSpace$-production
        name: $nameSpace$-application
        description: Application production
        issuesEnabled: "true"
        mergeRequestsEnabled: "true"
        wikiEnabled: "true"
        snipitsEnabled: "true"
        visibility: "2"
        targetName: gitlab
        gitSshHost: {{ .Values.gitlab_ssh_host | quote }}
        createWebhook: "false"
        
    
    # create a git file so there's something in the repo
    - taskType: customTask
      className: com.tremolosecurity.unison.gitlab.provisioning.tasks.CreateGitFile
      params:
        targetName: gitlab
        namespace: $nameSpace$-production
        project: $nameSpace$-application
        branch: main
        path: README.md
        content: |-
          # $nameSpace$-application 
  
          Fork this project to create to create your application.
        commitMessage: initializing the repository

    # approvers need to be able to merge pull requests
    - taskType: customTask
      className: com.tremolosecurity.unison.gitlab.provisioning.tasks.AddGroupToProject
      params:
        groupName: k8s-namespace-owners-k8s-$nameSpace$-internal
        targetName: gitlab
        accessLevel: MAINTAINER

    # operations and developer staff need to be able to fork projects
    - taskType: customTask
      className: com.tremolosecurity.unison.gitlab.provisioning.tasks.AddGroupToProject
      params:
        groupName: k8s-namespace-operations-k8s-$nameSpace$-internal
        targetName: gitlab
        accessLevel: DEVELOPER

    - taskType: customTask
      className: com.tremolosecurity.unison.gitlab.provisioning.tasks.AddGroupToProject
      params:
        groupName: k8s-namespace-developer-k8s-$nameSpace$-internal
        targetName: gitlab
        accessLevel: DEVELOPER

   



    