apiVersion: v1
kind: Service
metadata:
  name: k8gb-coredns-dual
  namespace: k8gb
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: udp-5353
    port: 53
    protocol: UDP
    targetPort: 5353
  - name: tcp-5353
    port: 53
    protocol: TCP
    targetPort: 5353
  selector:
    app.kubernetes.io/instance: k8gb
    app.kubernetes.io/name: coredns
  sessionAffinity: None
  type: LoadBalancer
