global:
  imagePullSecrets: []
k8gb:
  imageRepo: absaoss/k8gb
  imageTag: v0.8.7
  dnsZone: "gb.foowidgets.k8s" # dnsZone controlled by gslb
  edgeDNSZone: "foowidgets.k8s" # main zone which would contain gslb zone to delegate
  edgeDNSServer: "10.2.1.14" # use this DNS server as a main resolver to enable cross k8gb DNS based communication
  clusterGeoTag: "us-buf" # used for places where we need to distinguish between differnet Gslb instances
  extGslbClustersGeoTags: "us-nyc" # comma-separated list of external gslb geo tags to pair with
  reconcileRequeueSeconds: 30
  exposeCoreDNS: true # Create Service type LoadBalancer to expose CoreDNS
  log:
    format: simple # log format (simple,json)
    level: info # log level (panic,fatal,error,warn,info,debug,trace)
  splitBrainCheck: false
  metricsAddress: "0.0.0.0:8080"

coredns:
  serviceType: LoadBalancer
  isClusterService: false
  deployment:
    skipConfig: true
  image:
    repository: absaoss/k8s_crd
    tag: "v0.0.8"
  serviceAccount:
    create: true
    name: coredns
