k8gb:
  dnsZone: "gb.foowidgets.k8s" # dnsZone controlled by gslb
  edgeDNSZone: "foowidgets.k8s" # main zone which would contain gslb zone to delegate
  edgeDNSServers:
    - 10.2.1.14     # use this DNS server as a main resolver to enable cross k8gb DNS based communication
  clusterGeoTag: "us-buf" # used for places where we need to distinguish between differnet Gslb instances
  extGslbClustersGeoTags: "us-nyc" # comma-separated list of external gslb geo tags to pair with

  log:
    # -- log format (simple,json)
    format: simple # log format (simple,json)
    # -- log level (panic,fatal,error,warn,info,debug,trace)
    level: trace # log level (panic,fatal,error,warn,info,debug,trace)

coredns:
  # -- service: refer to https://www.k8gb.io/docs/service_upgrade.html for upgrading CoreDNS service steps
  isClusterService: false
  deployment:
    # -- Skip CoreDNS creation and uses the one shipped by k8gb instead
    skipConfig: true
  image:
    # -- CoreDNS CRD plugin image
    repository: absaoss/k8s_crd
    # -- image tag
    tag: v0.0.11
  # -- Creates serviceAccount for coredns
  serviceAccount:
    create: true
    name: coredns
  serviceType: LoadBalancer
