k8gb:
  dnsZone: "gb.foowidgets.k8s" # dnsZone controlled by gslb
  edgeDNSZone: "foowidgets.k8s" # main zone which would contain gslb zone to delegate
  edgeDNSServers:
    - 10.2.1.14     # use this DNS server as a main resolver to enable cross k8gb DNS based communication
  clusterGeoTag: "us-buf" # used for places where we need to distinguish between differnet Gslb instances
  extGslbClustersGeoTags: "us-nyc" # comma-separated list of external gslb geo tags to pair with

externaldns:
  # -- external-dns image repo:tag
  # It is important to use the image from k8gb external-dns fork to get the full
  # functionality. See links below
  # https://github.com/k8gb-io/external-dns
  # https://github.com/k8gb-io/external-dns/pkgs/container/external-dns
  image: ghcr.io/k8gb-io/external-dns:v0.13.4-azure-ns
  # -- external-dns sync interval
  interval: "20s"
  securityContext:
    # -- For more options consult https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.25/#securitycontext-v1-core
    runAsUser: 1000
    # -- For ExternalDNS to be able to read Kubernetes and AWS token files
    fsGroup: 65534 # For ExternalDNS to be able to read Kubernetes and AWS token files
    runAsNonRoot: true

coredns:
  # -- service: refer to https://www.k8gb.io/docs/service_upgrade.html for upgrading CoreDNS service steps
  isClusterService: false
  deployment:
    # -- Skip CoreDNS creation and uses the one shipped by k8gb instead
    skipConfig: true
  image:
    # -- CoreDNS CRD plugin image
    repository: absaoss/k8s_crd
    # -- image tag
    tag: v0.0.11
  # -- Creates serviceAccount for coredns
  serviceAccount:
    create: true
    name: coredns
  serviceType: LoadBalancer
