apiVersion: k8gb.absa.oss/v1beta1
kind: Gslb
metadata:
  name: gslb-failover-buf
  namespace: demo
spec:
  ingress:
    rules:
      - host: fe.gb.foowidgets.k8s # Desired GSLB enabled FQDN
        http:
          paths:
          - backend:
              service:
                name: nginx # Service name to enable GSLB for
                port:
                  name: http
            path: /
            pathType: Prefix
  strategy:
    type: failover # Global load balancing strategy
    primaryGeoTag: us-nyc # Primary cluster geo tag
