apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: coredns-registry-k8s-io-coredns-coredns-v1-10-1-remote-services
  namespace: kube-system
spec:
  action: Audit
  file:
    matchDirectories:
    - dir: /etc/ssh/
    matchPaths:
    - path: /var/log/wtmp
    - path: /var/run/utmp
    - path: /var/log/auth.log
    - path: /etc/passwd
    - path: /etc/shadow
  message: Warning! access sensitive files detected
  selector:
    matchLabels:
      k8s-app: kube-dns
  severity: 3
  tags:
  - MITRE
  - FIGHT
  - FGT1021
