apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: coredns-registry-k8s-io-coredns-coredns-v1-10-1-impair-defense
  namespace: kube-system
spec:
  action: Audit
  file:
    matchDirectories:
    - dir: /etc/apparmor.d/
      recursive: true
    - dir: /etc/sysconfig/selinux/
      recursive: true
    matchPaths:
    - path: /etc/selinux/semanage.conf
  message: Selinux Files Accessed by Unknown Process
  selector:
    matchLabels:
      k8s-app: kube-dns
  severity: 6
  tags:
  - MITRE
  - FGT1562
  - FIGHT
