apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: coredns-registry-k8s-io-coredns-coredns-v1-10-1-write-in-shm-dir
  namespace: kube-system
spec:
  action: Block
  file:
    matchDirectories:
    - dir: /dev/shm/
      readOnly: true
      recursive: true
  message: Alert! write to /dev/shm folder prevented.
  selector:
    matchLabels:
      k8s-app: kube-dns
  severity: 5
  tags:
  - MITRE_execution
  - MITRE
