apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ingress-nginx-controller-registry-k8s-io-ingress-nginx-controller-v1-7-1-sha256-7244b95e-cis-commandline-warning-banner
  namespace: ingress-nginx
spec:
  action: Block
  file:
    matchPaths:
    - path: /etc/motd
      readOnly: true
    - path: /etc/issue
      readOnly: true
    - path: /etc/issue.net
      readOnly: true
  message: Alert! write to warning banner file for standard command line login detected
  selector:
    matchLabels:
      app.kubernetes.io/component: controller
      app.kubernetes.io/instance: ingress-nginx
      app.kubernetes.io/name: ingress-nginx
      app.kubernetes.io/part-of: ingress-nginx
      app.kubernetes.io/version: 1.7.1
  severity: 5
  tags:
  - CIS
  - CIS_Linux
  - CIS_1.7_Warning_Banners
  - CIS_1.7.1_Command_Line_Warning_Banners
