apiVersion: v1
kind: Service
metadata:
  name: nginx-lb-pool02
  annotations:
    metallb.universe.tf/address-pool: pool-02
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    run: nginx-lb
  type: LoadBalancer

