apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: bitnami-nginx-latest-cronjob-cfg
spec:
  action: Audit
  file:
    matchDirectories:
    - dir: /var/spool/cron/
      recursive: true
    - dir: /var/cron/
      recursive: true
    - dir: /etc/cron.d/
      recursive: true
    - dir: /etc/cron.daily/
      recursive: true
    - dir: /etc/cron.hourly/
      recursive: true
    - dir: /etc/cron.monthly/
      recursive: true
    - dir: /etc/cron.weekly/
      recursive: true
    matchPaths:
    - path: /etc/crontab
  message: Alert! Access to cron job files/directories detected.
  selector:
    matchLabels:
      kubearmor.io/container.name: bitnami/nginx
  severity: 5
  tags:
  - NIST
  - SI-4
  - NIST_800-53_SI-4
  - CIS
  - CIS_Linux
  - CIS_5.1_Configure_Cron
