apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: bitnami-nginx-latest-file-system-mounts
spec:
  action: Audit
  message: Alert! file system mount detected
  process:
    matchPaths:
    - path: /bin/mount
    - path: /usr/bin/mount
    - path: /bin/umount
    - path: /usr/bin/umount
  selector:
    matchLabels:
      kubearmor.io/container.name: bitnami/nginx
  severity: 5
  tags:
  - CIS
  - CIS_Linux
  - CIS_4_Logging_and_Aduditing
  - CIS_4.1.1_Data_Retention
  - CIS_4.1.14_file_system_mount
