apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: bitnami-nginx-latest-maint-tools-access
spec:
  action: Audit
  message: restricted maintenance tool access attempt detected
  process:
    matchDirectories:
    - dir: /sbin/
      recursive: true
  selector:
    matchLabels:
      kubearmor.io/container.name: bitnami/nginx
  severity: 1
  tags:
  - PCI_DSS
  - MITRE
