apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: bitnami-nginx-latest-write-in-shm-dir
spec:
  action: Block
  file:
    matchDirectories:
    - dir: /dev/shm/
      readOnly: true
      recursive: true
  message: Alert! write to /dev/shm folder prevented.
  selector:
    matchLabels:
      kubearmor.io/container.name: bitnami/nginx
  severity: 5
  tags:
  - MITRE_execution
  - MITRE
