---
apiVersion: openunison.tremolo.io/v1
kind: Workflow
metadata:
  name: deploy-external-secret-operator
  namespace: {{ .Release.Namespace }}
spec:
  description: Deploy the external secret operator
  inList: false
  label: Deploy the exeternal secret operator
  orgId: 43625c4c-43a5-4e48-89da-7005a60cfcff
  tasks: |-
    - taskType: customTask
      className: com.tremolosecurity.provisioning.tasks.CreateK8sObject
      params:
        targetName: k8s
        template: |-
          kind: Namespace
          apiVersion: v1
          metadata:
            name: external-secrets
            labels:
              name: external-secrets
              tremolo.io/request-access: "false"
            annotations:
              tremolo.io/managedByGit: "$useGit$"
              $gitUrlAnnotation$
        srcType: yaml
        writeToRequest: "true"
        requestAttribute: git-secret-cluster-k8s-$nameSpace$-eso
        path: /yaml/cluster/namespaces/external-secrets.yaml

    # GitOps - push to cluster repo
    - taskType: customTask
      className: com.tremolosecurity.provisioning.tasks.PushToGit
      params:
        secretName: openunison-git-$nameSpace$-$env$-key
        nameSpace: openunison
        target: k8s
        keyName: id_rsa
        gitRepo: git@{{ .Values.gitlab_ssh_host }}:$nameSpace$-$env$/$nameSpace$-ops.git
        requestObject: git-secret-cluster-k8s-$nameSpace$-eso
        commitMsg: $env$ external secret operator for workflow $WORKFLOW.id$

    # wait for the namespaces to sync
    - taskType: customTask
      className: com.tremolosecurity.provisioning.tasks.WaitForStatus
      params:
        holdingTarget: k8s
        namespace: openunison
        target: k8s-$nameSpace$-$env$
        uri: /api/v1/namespaces/external-secrets
        label: wait-ns-$env$-external-secrets-$nameSpace$
        conditions: []

    - taskType: customTask
      className: com.tremolosecurity.provisioning.customTasks.PrintUserInfo
      params:
        message: "Nolonger waiting for external-secrets"


    - taskType: customTask
      className: com.tremolosecurity.provisioning.tasks.CreateK8sObject
      params: 
        targetName: k8s
        template: |-
            apiVersion: batch/v1
            kind: Job
            metadata:
              name: onboard-vcluster-external-secrets-$env$-$nameSpace$
              namespace: {{ .Release.Namespace }}
              labels:
                name: onboard-vcluster-external-secrets-$env$-$nameSpace$
            spec:
              parallelism: 1
              completions: 1
              backoffLimit: 5
              selector:
                matchLabels:
                  job-name: onboard-vcluster-external-secrets-$env$-$nameSpace$
              template:
                metadata:
                  name: onboard-vcluster-external-secrets-$env$-$nameSpace$
                  namespace: {{ .Release.Namespace }}
                  labels:
                    job-name: onboard-vcluster-external-secrets-$env$-$nameSpace$
                spec:
                    containers:
                    - args:
                        - bash
                        - /scripts/deploy-eso-to-vcluster.sh
                      image: {{ .Values.vcluster.job_image }}
                      imagePullPolicy: Always
                      name: vcluster-onboard-eso
                      resources: {}
                      volumeMounts:
                        - mountPath: /scripts
                          name: vcluster-scripts
                        - mountPath: /etc/openunison
                          name: certs
                      env:
                      - name: CP_HOST
                        value: k8sou.{{ .Values.cp_dns_suffix}}
                      - name: ENV_NAME
                        value: k8s-kubernetes-$env$
                      - name: TARGET_URL
                        value: https://oumgmt-$nameSpace$.$domain$
                      - name: ORCHESTRA_NAME
                        value: {{ .Values.openunison.orchestra_name }}
                      - name: TARGET_NAME
                        value: "k8s-$nameSpace$-$env$"
                      securityContext:
                        allowPrivilegeEscalation: false
                        capabilities:
                          drop:
                          - "all"
                    dnsPolicy: ClusterFirst
                    serviceAccount: openunison-{{ .Values.openunison.orchestra_name }}
                    serviceAccountName: openunison-{{ .Values.openunison.orchestra_name }}
                    restartPolicy: OnFailure
                    {{ if .Capabilities.APIVersions.Has "project.openshift.io/v1/Project" }}
                    securityContext:
                      seccompProfile:
                        type: RuntimeDefault
                      runAsNonRoot: true
                    {{ else }}
                    securityContext:
                      fsGroup: 433
                      supplementalGroups: [433]
                      seccompProfile:
                        type: RuntimeDefault
                      runAsNonRoot: true
                      runAsUser: 431
                      runAsGroup: 433
                    {{ end }}
                    volumes:
                    - name: vcluster-scripts
                      configMap:
                        name: vcluster-scripts
                    - name: certs
                      secret:
                        secretName: unison-ca
        srcType: yaml

    # wait for the namespaces to sync
    - taskType: customTask
      className: com.tremolosecurity.provisioning.tasks.WaitForStatus
      params:
        holdingTarget: k8s
        namespace: openunison
        target: k8s-$nameSpace$-$env$
        uri: /api/v1/namespaces/external-secrets/configmaps/deployment-complete
        label: wait-ns-$env$-external-secrets-job-deployment-$nameSpace$
        conditions: []

    # integration complete, cleanup
    - taskType: customTask
      className: com.tremolosecurity.provisioning.tasks.DeleteK8sObject
      params:
        targetName: k8s-kubernetes-$env$
        kind:  ConfigMap
        url: /api/v1/namespaces/external-secrets/configmaps/deployment-complete

    - taskType: customTask
      className: com.tremolosecurity.provisioning.customTasks.PrintUserInfo
      params:
        message: "Nolonger waiting for external-secrets deployment"  

    