apiVersion: v1
kind: Namespace
metadata:
  name: sales
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: index
  namespace: sales
data:
  index.html: |
    <html>
    <h1>** ERROR **</h1>
    </br>
    <h1>Hi! Connection Denied </h1>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-fe
  namespace: sales
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
            - name: index-file
              mountPath: /usr/share/nginx/html/
      volumes:
      - name: index-file
        configMap:
          name: index
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-fe
  namespace: sales
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
