---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-remote-tokens
  namespace: argocd
data:
  remote-token.sh: |-
    #!/bin/bash

    REMOTE_TOKEN=$(/custom-tools/curl --insecure -H "Authorization: Bearer $(<$3)" https://$1/api/get-target-token?targetName=$2 2>/dev/null)

    echo -n "{\"apiVersion\": \"client.authentication.k8s.io/v1\",\"kind\": \"ExecCredential\",\"status\": {\"token\": \"$REMOTE_TOKEN\"}}"