---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: mysql
data:
  mysql-tls.cnf: |-
    [mysqld]
    ssl-ca=/etc/mysql-tls/ca.crt
    ssl-cert=/etc/mysql-tls/tls.crt
    ssl-key=/etc/mysql-tls/tls.key
    require_secure_transport=ON
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: mysql
  name: mysql
  namespace: mysql
spec:
  serviceName: mysql
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: "mysql"
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mysql
    spec:
      containers:
      - env:
        - name: MYSQL_ROOT_PASSWORD
          value: start123
        - name: MYSQL_DATABASE
          value: unison
        - name: MYSQL_USER
          value: unison
        - name: MYSQL_PASSWORD
          value: startt123
        image: mysql
        imagePullPolicy: Always
        name: mysql
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-data
        - mountPath: /etc/mysql-tls
          name: mysql-tls
        - mountPath: /etc/mysql/conf.d
          name: mysql-config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: mysql-tls
        secret:
          secretName: mysql-tls
      - name: mysql-config
        configMap:
          name: mysql-config
  volumeClaimTemplates:
  - metadata:
      name: mysql-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql
  name: mysql
  namespace: mysql
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mysql
  sessionAffinity: None
  type: ClusterIP