apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: kubearmor-controller-gcr-io-kubebuilder-kube-rbac-proxy-v0-8-0-remote-services
  namespace: kube-system
spec:
  action: Audit
  file:
    matchDirectories:
    - dir: /etc/ssh/
    matchPaths:
    - path: /var/log/wtmp
    - path: /var/run/utmp
    - path: /var/log/auth.log
    - path: /etc/passwd
    - path: /etc/shadow
  message: Warning! access sensitive files detected
  selector:
    matchLabels:
      kubearmor-app: kubearmor-controller
  severity: 3
  tags:
  - MITRE
  - FIGHT
  - FGT1021
