apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: kubearmor-controller-gcr-io-kubebuilder-kube-rbac-proxy-v0-8-0-system-owner-discovery
  namespace: kube-system
spec:
  action: Block
  message: System owner discovery command execution denied
  process:
    matchPaths:
    - path: /usr/bin/who
    - path: /usr/bin/w
    - path: /usr/bin/id
    - path: /usr/bin/whoami
  selector:
    matchLabels:
      kubearmor-app: kubearmor-controller
  severity: 3
  tags:
  - MITRE
  - MITRE_T1082_system_information_discovery
