apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: kubearmor-controller-kubearmor-kubearmor-controller-latest-maint-tools-access
  namespace: kube-system
spec:
  action: Audit
  message: restricted maintenance tool access attempt detected
  process:
    matchDirectories:
    - dir: /sbin/
      recursive: true
  selector:
    matchLabels:
      kubearmor-app: kubearmor-controller
  severity: 1
  tags:
  - PCI_DSS
  - MITRE
