apiVersion: openunison.tremolo.io/v1
kind: Target
metadata:
  name: dev-mysql
  namespace: {{ .Release.Namespace }}
spec:
  className: com.tremolosecurity.provisioning.core.providers.BasicDB
  params:
  - name: driver
    value: com.mysql.jdbc.Driver
  - name: url
    value: jdbc:mysql://mysql.{{ .Values.dev_dns_suffix }}
  - name: user
    value: root
  - name: maxCons
    value: "10"
  - name: maxIdleCons
    value: "10"
  - name: validationQuery
    value: SELECT 1
  - name: userTable
    value: localUsers
  - name: userPrimaryKey
    value: userId
  - name: userName
    value: sub
  - name: groupMode
    value: ManyToMany
  - name: groupTable
    value: localGroups
  - name: groupName
    value: name
  - name: groupUserKey
    value: userId
  - name: groupLinkTableName
    value: userGroups
  - name: groupGroupKey
    value: groupId
  - name: groupPrimaryKey
    value: groupId
  - name: userSQL
    value: ""
  - name: groupSQL
    value: ""
  - name: customProvider
    value: ""
  - name: readOnly
    value: "true"
  secretParams:
  - name: password
    secretKey: dev
    secretName: mysql-passwords
  targetAttributes:
  - name: sub
    source: sub
    sourceType: user
  - name: mail
    source: mail
    sourceType: user
  - name: firstName
    source: firstName
    sourceType: user
  - name: lastName
    source: lastName
    sourceType: user