package k8senforceingress

test_ingress_allowed {
    not missingIngressLabel with input as {"apiVersion":"admission.k8s.io/v1","kind":"AdmissionReview","parameters":{"registries":["x","quay.io/"]},"review":{"uid":"705ab4f5-6393-11e8-b7cc-42010a800002","kind":{"group":"autoscaling","version":"v1","kind":"Scale"},"resource":{"group":"apps","version":"v1","resource":"deployments"},"subResource":"scale","requestKind":{"group":"autoscaling","version":"v1","kind":"Scale"},"requestResource":{"group":"apps","version":"v1","resource":"deployments"},"requestSubResource":"scale","name":"my-deployment","namespace":"ns-with-ingress","operation":"CREATE","userInfo":{"username":"admin","uid":"014fbff9a07c","groups":["system:authenticated","my-admin-group"],"extra":{"some-key":["some-value1","some-value2"]}},"object":{"apiVersion":"networking.k8s.io/v1","kind":"Ingress","metadata":{"annotations":{"cert-manager.io/cluster-issuer":"letsencrypt","kubernetes.io/ingress.class":"nginx"},"creationTimestamp":"2022-06-29T14:08:37Z","generation":1,"labels":{"app.kubernetes.io/instance":"keycloak"},"name":"keycloak","namespace":"ns-with-ingress","resourceVersion":"186243","uid":"623ee236-c738-4883-8b7e-e3d4c5718389"},"spec":{"rules":[{"host":"keycloak.lab.tremolo.dev","http":{"paths":[{"backend":{"service":{"name":"keycloak","port":{"number":8080}}},"path":"/","pathType":"ImplementationSpecific"}]}}],"tls":[{"hosts":["keycloak.lab.tremolo.dev"],"secretName":"keycloak-tls-certificate"}]}},"oldObject":null,"options":null,"dryRun":false}} with data.inventory as {"cluster":{"v1":{"Namespace":{"ns-with-ingress":{"metadata":{"labels":{"allowingress":"true"}}},"ns-without-ingress":{"metadata":{}}}}}}
}

test_not_ingress_allowed_with_label {
    missingIngressLabel with input as {"apiVersion":"admission.k8s.io/v1","kind":"AdmissionReview","parameters":{"registries":["x","quay.io/"]},"review":{"uid":"705ab4f5-6393-11e8-b7cc-42010a800002","kind":{"group":"autoscaling","version":"v1","kind":"Scale"},"resource":{"group":"apps","version":"v1","resource":"deployments"},"subResource":"scale","requestKind":{"group":"autoscaling","version":"v1","kind":"Scale"},"requestResource":{"group":"apps","version":"v1","resource":"deployments"},"requestSubResource":"scale","name":"my-deployment","namespace":"ns-without-ingress","operation":"CREATE","userInfo":{"username":"admin","uid":"014fbff9a07c","groups":["system:authenticated","my-admin-group"],"extra":{"some-key":["some-value1","some-value2"]}},"object":{"apiVersion":"networking.k8s.io/v1","kind":"Ingress","metadata":{"annotations":{"cert-manager.io/cluster-issuer":"letsencrypt","kubernetes.io/ingress.class":"nginx"},"creationTimestamp":"2022-06-29T14:08:37Z","generation":1,"labels":{"app.kubernetes.io/instance":"keycloak"},"name":"keycloak","namespace":"ns-without-ingress","resourceVersion":"186243","uid":"623ee236-c738-4883-8b7e-e3d4c5718389"},"spec":{"rules":[{"host":"keycloak.lab.tremolo.dev","http":{"paths":[{"backend":{"service":{"name":"keycloak","port":{"number":8080}}},"path":"/","pathType":"ImplementationSpecific"}]}}],"tls":[{"hosts":["keycloak.lab.tremolo.dev"],"secretName":"keycloak-tls-certificate"}]}},"oldObject":null,"options":null,"dryRun":false}} with data.inventory as {"cluster":{"v1":{"Namespace":{"ns-with-ingress":{"metadata":{"labels":{"allowingress":"true"}}},"ns-without-ingress":{"metadata":{"labels":{"allowingress":"false"}}}}}}}
}

test_not_ingress_allowed_without_label {
    missingIngressLabel with input as {"apiVersion":"admission.k8s.io/v1","kind":"AdmissionReview","parameters":{"registries":["x","quay.io/"]},"review":{"uid":"705ab4f5-6393-11e8-b7cc-42010a800002","kind":{"group":"autoscaling","version":"v1","kind":"Scale"},"resource":{"group":"apps","version":"v1","resource":"deployments"},"subResource":"scale","requestKind":{"group":"autoscaling","version":"v1","kind":"Scale"},"requestResource":{"group":"apps","version":"v1","resource":"deployments"},"requestSubResource":"scale","name":"my-deployment","namespace":"ns-without-ingress","operation":"CREATE","userInfo":{"username":"admin","uid":"014fbff9a07c","groups":["system:authenticated","my-admin-group"],"extra":{"some-key":["some-value1","some-value2"]}},"object":{"apiVersion":"networking.k8s.io/v1","kind":"Ingress","metadata":{"annotations":{"cert-manager.io/cluster-issuer":"letsencrypt","kubernetes.io/ingress.class":"nginx"},"creationTimestamp":"2022-06-29T14:08:37Z","generation":1,"labels":{"app.kubernetes.io/instance":"keycloak"},"name":"keycloak","namespace":"ns-without-ingress","resourceVersion":"186243","uid":"623ee236-c738-4883-8b7e-e3d4c5718389"},"spec":{"rules":[{"host":"keycloak.lab.tremolo.dev","http":{"paths":[{"backend":{"service":{"name":"keycloak","port":{"number":8080}}},"path":"/","pathType":"ImplementationSpecific"}]}}],"tls":[{"hosts":["keycloak.lab.tremolo.dev"],"secretName":"keycloak-tls-certificate"}]}},"oldObject":null,"options":null,"dryRun":false}} with data.inventory as {"cluster":{"v1":{"Namespace":{"ns-with-ingress":{"metadata":{"labels":{"allowingress":"true"}}},"ns-without-ingress":{"metadata":{"labels":[]}}}}}}
}

test_not_ingress_allowed_no_labels {
    missingIngressLabel with input as {"apiVersion":"admission.k8s.io/v1","kind":"AdmissionReview","parameters":{"registries":["x","quay.io/"]},"review":{"uid":"705ab4f5-6393-11e8-b7cc-42010a800002","kind":{"group":"autoscaling","version":"v1","kind":"Scale"},"resource":{"group":"apps","version":"v1","resource":"deployments"},"subResource":"scale","requestKind":{"group":"autoscaling","version":"v1","kind":"Scale"},"requestResource":{"group":"apps","version":"v1","resource":"deployments"},"requestSubResource":"scale","name":"my-deployment","namespace":"ns-without-ingress","operation":"CREATE","userInfo":{"username":"admin","uid":"014fbff9a07c","groups":["system:authenticated","my-admin-group"],"extra":{"some-key":["some-value1","some-value2"]}},"object":{"apiVersion":"networking.k8s.io/v1","kind":"Ingress","metadata":{"annotations":{"cert-manager.io/cluster-issuer":"letsencrypt","kubernetes.io/ingress.class":"nginx"},"creationTimestamp":"2022-06-29T14:08:37Z","generation":1,"labels":{"app.kubernetes.io/instance":"keycloak"},"name":"keycloak","namespace":"ns-without-ingress","resourceVersion":"186243","uid":"623ee236-c738-4883-8b7e-e3d4c5718389"},"spec":{"rules":[{"host":"keycloak.lab.tremolo.dev","http":{"paths":[{"backend":{"service":{"name":"keycloak","port":{"number":8080}}},"path":"/","pathType":"ImplementationSpecific"}]}}],"tls":[{"hosts":["keycloak.lab.tremolo.dev"],"secretName":"keycloak-tls-certificate"}]}},"oldObject":null,"options":null,"dryRun":false}} with data.inventory as {"cluster":{"v1":{"Namespace":{"ns-with-ingress":{"metadata":{"labels":{"allowingress":"true"}}},"ns-without-ingress":{"metadata":{}}}}}}
}